server:
  servlet:
    context-path: /api
spring:
  application:
    name: ai-code-generate-backend
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.rescld.aicodegeneratebackend.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn